ramenia/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

from django.urls import include
urlpatterns += [
    path('app/', include('rameniaapp.urls')),
]

from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='app/', permanent=True)),
]



from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rameniaapp/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView
from rameniaapp.forms import PrettyAuthenticationForm

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    # Noodle view and noodle actions
    path('noodle/<int:noodle_id>', views.view_noodle, name="noodle"),
    path('noodle/add', views.ramen_create_view, name="add_noodle"),
    path('noodle/<int:noodle_id>/edit', views.ramen_edit_view, name="edit_ramen"),
    path('noodle/<int:noodle_id>/review', views.ramen_review_view, name="review_ramen"),
    path('noodle/<int:id>/report', views.NoodleReportForm.as_view(), name="noodle_report"), 
    
    # User related views and report page
    path('user/<int:user_id>', views.view_profile, name="profile"),
    path('user/<int:user_id>/follow', views.follow_profile, name ="follow_profile"),
    path('user/<int:user_id>/following', views.view_following, name ="following"),
    path('user/<int:id>/report', views.ProfileReportForm.as_view(), name="profile_report"), 
    
    # Routes for the default django authentication module and our account action pages
    path('', include('django.contrib.auth.urls')),
    path('login', LoginView.as_view(template_name='registration/login.html', authentication_form=PrettyAuthenticationForm), name="login"),
    path('register', views.register, name="register"),
    path('edit_profile', views.edit_profile, name="edit_profile"),
    path('settings', views.change_password, name="change_password"),

    # Lists views
    path('list/<int:list_id>', views.view_list, name="list"),
    path('user/<int:user_id>/lists', views.view_user_lists, name="user_lists"),
    
    # Moderator links page
    path('mod', views.view_mod_page, name="moderator"),

    # Moderator edit views (including filtering- not yet fully implemented in UI) and actions
    path('mod/edits', views.EditsList.as_view(), name="all_edits"),
    path('mod/edits/noodle/new', views.EditsList.as_view(), {'new' : True}, name="new_noodles"),
    path('mod/edits/noodle/<int:noodle_id>', views.EditsList.as_view(), name="edits_by_noodle"),
    path('mod/edits/user/<int:user_id>', views.EditsList.as_view(), name="edits_by_user"),
    path('mod/edits/approve/<int:edit_id>', views.apply_edit, name="approve_edit"),
    path('mod/edits/reject/<int:edit_id>', views.reject_edit, name="reject_edit"),
    
    # Mod report views- filtering by object not yet implemented
    path('mod/reports/noodle/', views.NoodleReportList.as_view(), name="noodle_reports"),
    path('mod/reports/noodle/<int:item_id>', views.NoodleReportList.as_view(), name="reports_by_noodle"),
    path('mod/reports/review/', views.ReviewReportList.as_view(), name="review_reports"),
    path('mod/reports/review/<int:item_id>', views.ReviewReportList.as_view(), name="reports_by_review"),
    path('mod/reports/profile/', views.ProfileReportList.as_view(), name="profile_reports"),
    path('mod/reports/profile/<int:item_id>', views.ProfileReportList.as_view(), name="reports_by_profile"),

    # Mod report actions
    path('mod/reports/<int:report_id>/ignore', views.ignore_report, name="ignore_report"),
    path('mod/reports/<int:report_id>/status/<str:status>', views.update_report_status, name="update_report_status"),
    path('mod/reports/<str:report_type>/ban/<int:user_id>', views.ban_user, name="ban_user"),
    path('mod/reports/<int:report_id>/edit/', views.ignore_report, name="report_edit"),
    path('mod/reports/<int:report_id>/delete_content/', views.delete_content, name="delete_content"),

    path('search', views.view_search, name="search"),
    path('notifications', views.view_notifications, name="notifications"),

    # REST API views

    # get the noodles of list_id
    path('api/list/<int:list_id>', views.list_rest, name="list_rest"),
    
    # modify list_id. PUT adds noodle_id to the list, DELETE removes noodle_id from the list
    path('api/list/<int:list_id>/<int:noodle_id>', views.list_mod_rest, name="list_mod_rest"),

    # returns a json list of user_id's lists
    path('api/user/<int:user_id>/lists', views.user_lists_rest, name="user_lists_rest"),

    # returns search results
    path('api/search', views.search_rest, name="search_rest"),

    # returns notification results
    path('api/notifications/<int:page>', views.notifications_rest, name="notifications_rest"),

    # returns a review
    path('api/review/<int:review>', views.review_rest, name="review_rest"),

    # returns reviews for a noodle
    path('api/reviews/<int:noodle>', views.reviews_rest, name="reviews_rest")
]

rameniaapp/models/actionhook.py
from django.db import models

class ActionHook(models.Model):
    hook_name = models.CharField(max_length=80)
    params = models.JSONField()

rameniaapp/models/noodle.py
from django.db import models
from django.conf import settings
from datetime import date

class Noodle(models.Model):
    name = models.CharField(max_length=60)
    #TODO: Validations and character limit enforcement are in forms
    # JSON generally assumes following fields: 
    # Line, Flavor, Description, Manufacturer, Released
    metadata = models.JSONField(null=True, blank=True)
    tags = models.ManyToManyField("rameniaapp.Tag", blank=True)
    # Currently assume that noodles are editable and we want a history
    created_timestamp = models.DateField(auto_now=False, default=date.today)
    edited_timestamp = models.DateField(auto_now=False, default=date.today)
    editor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)

# Because of the one to many relationship of reviews/photos, create a separate model
class NoodleImage(models.Model):
    image = models.ImageField(default="noodles.png")
    main = models.BooleanField(default=False)
    noodle = models.ForeignKey(Noodle, on_delete=models.CASCADE)
    timestamp = models.DateField(auto_now_add=False, default=date.today)
    is_default = models.BooleanField(default=False)
    uploader = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)

rameniaapp/models/report.py
from django.db import models
from django.conf import settings

class Report(models.Model):
    # Restrict choices for certain fields- format is 'stored value', 'readable value'
    REPORT_TYPE_CHOICES = [('RV', "Review"), ('PF', "Profile"), ('ND', "Noodle")]
    REASON_CHOICES = [('AD', "Advertising"), ('HR', "Harassment"), 
                    ('IC', "Copyrighted or illegal content"), 
                    ('GS', "Disgusting or disturbing content")]
    STATUS_CHOICES = [('OP', "Open"), ('ED', "Resolved"), ('SP', "Spam")]
    reporter = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    type = models.CharField(max_length=2, choices=REPORT_TYPE_CHOICES)
    reason = models.CharField(max_length=2, choices=REASON_CHOICES)
    status = models.CharField(max_length=2, choices=STATUS_CHOICES)

# Django does not allow polymorphic relationships without external modules,
# so we just inherit
class ReviewReport(Report):
    review = models.ForeignKey("rameniaapp.Review", on_delete=models.CASCADE)

class ProfileReport(Report):
    profile = models.ForeignKey("rameniaapp.Profile", on_delete=models.CASCADE)

class NoodleReport(Report):
    noodle = models.ForeignKey("rameniaapp.Noodle", on_delete=models.CASCADE)

rameniaapp/models/review.py
from django.db import models
from django.conf import settings

class Review(models.Model):
    # This is another format for restricting choices for specifically
    # integers. See the documentation for any further queries.
    class Ratings(models.IntegerChoices):
        ONE_STAR = 1
        TWO_STAR = 2
        THREE_STAR = 3
        FOUR_STAR = 4
        FIVE_STAR = 5

    title = models.CharField(max_length=60)
    body = models.CharField(max_length=1000)
    rating = models.IntegerField(choices=Ratings.choices)
    reviewer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    noodle = models.ForeignKey("rameniaapp.Noodle", on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, editable=False, null=False, blank=False)

# Because of the one to many relationship of reviews/photos, create a separate model
class ReviewImage(models.Model):
    image = models.ImageField()
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    timestamp = models.DateField(auto_now_add=True)
    uploader = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

rameniaapp/forms/create_list.py
from django import forms
from django.forms.widgets import TextInput

class ListCreateForm(forms.Form):
    list_name = forms.CharField(label="Name", max_length=60, widget=TextInput(attrs={'class':'form-control'}))

rameniaapp/forms/edit_profile.py
from django import forms
from rameniaapp.models import Profile
from django.forms.widgets import TextInput, Textarea, FileInput

class EditProfileForm(forms.Form):
     '''Form for edit profile view'''
     profile_name = forms.CharField(label="Profile Name", max_length=80, widget=TextInput(attrs={'class':'form-control'}))
     profile_pic = forms.ImageField(label="Profile Picture", required=False, widget=FileInput(attrs={'class':'form-control-file'}))
     description = forms.CharField(label= "Description", max_length=300, required=False, widget=TextInput(attrs={'class':'form-control'}))

rameniaapp/forms/login.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.forms.widgets import TextInput

class PrettyAuthenticationForm(AuthenticationForm):
    '''django.auth AuthenticationForm with Bootstrap styling override'''
    def __init__(self, *args, **kwargs):
        super(PrettyAuthenticationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class':'form-control'})
        self.fields['password'].widget.attrs.update({'class':'form-control'})

rameniaapp/forms/noodle_forms.py
from django import forms
from django.forms.widgets import TextInput, Textarea, FileInput
from rameniaapp.models import Edit
from rameniaapp.models import Tag

class TagsField(forms.Field):
    '''Field for specifying expected tags and turning input strings into usable data'''
    # This code based on example code in Django docs
    # https://docs.djangoproject.com/en/3.1/ref/forms/validation/
    def to_python(self, value):
        if not value:
            return []
        return value.split(',')

    def validate(self, value):
        super().validate(value)

class NoodleForm(forms.Form):
    '''Generic class for noodle fields, couldn't use modelform due to JSON, do not use in views'''
    name = forms.CharField(max_length=50, widget=TextInput(attrs={'class':'form-control'}))
    manufacturer = forms.CharField(max_length=50, widget=TextInput(attrs={'class':'form-control'}))
    description = forms.CharField(max_length=200, widget=Textarea(attrs={'class':'form-control'}))
    flavor = forms.CharField(max_length=50, widget=TextInput(attrs={'class':'form-control'}))
    released = forms.CharField(max_length=50, widget=TextInput(attrs={'class':'form-control'}))
    line = forms.CharField(max_length=50, widget=TextInput(attrs={'class':'form-control'}))
    tags = TagsField(required=False, widget=TextInput(attrs={'class':'form-control'}))

class AddNoodleForm(NoodleForm):
    '''Form for add noodle view'''
    image = forms.ImageField(required = False, widget=FileInput(attrs={'class':'form-control-file'}))

class EditNoodleForm(NoodleForm):
    '''Form for edit noodle view'''
    image = forms.ImageField(required = False, widget=FileInput(attrs={'class':'form-control-file'}))

rameniaapp/forms/password_change.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm
from django.forms.widgets import TextInput

#TODO: Should we rename this?
class ChangePasswordForm(PasswordChangeForm):
    '''django.auth PasswordChangeForm with Bootstrap styling override'''
    def __init__(self, *args, **kwargs):
        super(ChangePasswordForm, self).__init__(*args, **kwargs)
        self.fields['old_password'].widget.attrs.update({'class':'form-control'})
        self.fields['new_password1'].widget.attrs.update({'class':'form-control'})
        self.fields['new_password2'].widget.attrs.update({'class':'form-control'})

rameniaapp/forms/registration.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms.widgets import FileInput

class RegistrationForm(UserCreationForm):
    '''Form for user registration that allows profile setup'''
    profile_name = forms.CharField(label="Profile Name (this is not used to login)", max_length=80)
    profile_pic = forms.ImageField(label="Profile Picture", required=False, widget=FileInput(attrs={'class':'form-control-file'}))
    
    def __init__(self, *args, **kwargs):
        # This is the correct place to override the bootstrap styling
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.widget = forms.TextInput(attrs={'class':'tag_field'})
        self.fields['username'].widget.attrs.update({'class':'form-control'})
        self.fields['password1'].widget.attrs.update({'class':'form-control'})
        self.fields['password2'].widget.attrs.update({'class':'form-control'})
        self.fields['profile_name'].widget.attrs.update({'class':'form-control'})

rameniaapp/forms/search.py
from django import forms
from django.forms.widgets import TextInput

class SearchForm(forms.Form):
    text_search = forms.CharField(label="Search", max_length=100, widget=TextInput(attrs={'class':'form-control'}))

rameniaapp/views/account.py
from django.shortcuts import render, HttpResponseRedirect
from rameniaapp.forms import RegistrationForm, EditProfileForm
from rameniaapp.models import Profile
from django.contrib.auth import authenticate, login
from django.contrib import messages

def register(request):
    BLANK_METADATA = {"Rated": 0, "Tried": 0, "Reviewed": 0, "Reputation": 0, \
    "Description": "", "Entries Made": 0, "Noodle Edits": 0}
    if request.method == "POST":
        form = RegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            if request.FILES:
                file = list(request.FILES.keys())[0]
                profile = Profile(name=form.cleaned_data["profile_name"], \
                                profile_pic=request.FILES[file], \
                                user=user, metadata=BLANK_METADATA)
                profile.save()
                
            else:
                profile = Profile(name=form.cleaned_data["profile_name"], \
                                user=user, metadata=BLANK_METADATA)
                profile.save()
                messages.add_message(request, messages.SUCCESS, "Account created successfully")
            #Backend param is not specified if this isn't done first
            user = authenticate(username=form.cleaned_data["username"],\
                                password=form.cleaned_data["password1"])
            login(request, user)
            return HttpResponseRedirect('/app/')
    else:
        form = RegistrationForm()
    return render(request, 'registration/register.html', {"form": form})

rameniaapp/views/add_ramen.py
from django.shortcuts import render,HttpResponse, HttpResponseRedirect
from django.template import loader
from django.conf import settings
from rameniaapp.forms import AddNoodleForm
from rameniaapp.models import Noodle, NoodleImage, Edit, Tag
from .edit_util import apply_change
from django.contrib.auth.decorators import login_required
from django.contrib import messages

@login_required(login_url="/app/login")
def ramen_create_view(request):
    '''View for handling add noodle form'''
    form = AddNoodleForm()
    # If this is a POST request then process the Form data
    if request.method == 'POST':
        user = request.user
        # Create a form instance and populate it with data from the request of the user
        form = AddNoodleForm(request.POST or None, request.FILES)
        # Check if the form is valid:
        if form.is_valid():
            print(form.cleaned_data)
            # Helps with clean format
            metadata = { "Name": form.cleaned_data["name"], "Description": form.cleaned_data["description"], \
                        "Flavor": form.cleaned_data["flavor"], \
                        "Manufacturer": form.cleaned_data["manufacturer"], \
                        "Released": form.cleaned_data["released"], "Line": form.cleaned_data["line"], \
                        "Tags": form.cleaned_data["tags"] }
            edit = Edit(editor = user, change = metadata)
            # Standard code to get file from request and set as edit's image
            if request.FILES:
                file = list(request.FILES.keys())[0]
                edit.image = request.FILES[file]
            edit.save()
            messages.add_message(request, messages.SUCCESS, "Entry submitted successfully- please wait for moderator approval")
            # redirect to a new URL:
            return HttpResponseRedirect('/app/')
    else:
        template = loader.get_template('add_ramen.html')
        context = {
            'form': form,
        }
        return HttpResponse(template.render(context, request))

rameniaapp/templates/ramen.html
{% extends "base.html" %}
{% block head_aux %}

{% if user.is_authenticated %}
{% comment %} JS to handle adding noodle to list w/o reload {% endcomment %}
<script>
$(document).ready(function(){
    // get the users list to add to the list dialog
    $.ajax({
        type: 'get',
        url: "{% url 'user_lists_rest' user.id %}",
        success: function(result) {
            for (i in result){
                var new_item = "<a class=\"listAddEntry dropdown-item\" data-list-id=\"" + result[i].id + "\">" + result[i].name + "</a>";
                $("#listAddDropdown").append(new_item);
                console.log(result[i]);
            }
        }
    });

    // bind the list entries to add the current noodl
    $(document).delegate('.listAddEntry','click',function(){
        $.ajax({
            type: 'put',
            url: "/app/api/list/" + $(this).data("list-id") + "/" + "{{ noodle.id }}",
            success: function(){
                console.log("added ramen");
                $("#actionsSection").append("<p>Added</p>");
            }
        });
    }); 
});
</script>
{% endif %}

<script>

// load all reviews for this noodle into the review section
function allReviews() {
    $.ajax({
        type: 'GET',
        url: "/app/api/reviews/{{ noodle.id }}",
        statusCode: {
            200: function(res){
                console.log("got results");
                if (res.length == 0) {
                    $("#error-text").removeClass("d-none");
                    $("#error-text").html("There are no reviews");
                } else {
                    $("#error-text").addClass("d-none");
                    $("#showAllReviews").addClass("d-none");
                    $("#reviewList").html(""); // clear reviews
                    
                    // load the template (see below for the actual template)
                    var itemTemplate = $("#reviewTemplate").html();

                    // for every review
                    res.forEach(function(item){
                        // make new template instance
                        var $item = $(itemTemplate);

                        // populate template params
                        $item.find("img[data-template='reviewerImg']").attr("src",item.reviewer.profile.profile_pic);
                        $item.find("li[data-template='reviewItem']").attr("href", "/app/user/" + item.reviewer.id);
                        $item.find("a[data-template='reviewerName']").text(item.reviewer.profile.name);
                        $item.find("a[data-template='reviewerName']").attr("href", "/app/user/" + item.reviewer.id);
                        $item.find("a[data-template='reviewTitle']").text(item.title);
                        $item.find("a[data-template='reviewTitle']").attr("href", "/app/noodle/{{noodle.id}}?focusReview=" + item.id);
                        $item.find("span[data-template='rating']").text(item.rating);
                        $item.find("p[data-template='reviewBody']").text(item.body);
                        $item.find("span[data-template='reviewTime']").text(item.created);

                        // load images into the template if it has any
                        if (item.images.length != 0) {
                            $item.find("div[data-template='reviewImages']").removeClass("d-none");
                        }
                        item.images.forEach(function (item){
                            $item.find("div[data-template='reviewImages']").append(
                                "<a href=\"" + item.image + "\"><img src=\"" + item.image +"\" height=\"150\"></a>" 
                            );
                        });
                        

                        $("#reviewList").append($item);
                        console.log(item)
                    });
                }
            },
            403: function(){
                $("#error-text").removeClass("d-none");
                $("#error-text").html("Error retrieving notifications");
            }
        }
    });
}

// load a single review into the review section
function focusReview(review_id) {
    $.ajax({
        type: 'GET',
        url: "/app/api/review/" + review_id,
        statusCode: {
            200: function(res){
                console.log("got results");
                if (!res) {
                    $("#error-text").removeClass("d-none");
                    $("#error-text").html("Not a valid review");
                } else {
                    $("#error-text").addClass("d-none");
                    $("#reviewList").html(""); // clear reviews
                    
                    // works similar to the multiple review case but only adds one
                    var itemTemplate = $("#reviewTemplate").html();
                        var $item = $(itemTemplate);
                        $item.find("img[data-template='reviewerImg']").attr("src",res.reviewer.profile.profile_pic);
                        $item.find("li[data-template='reviewItem']").attr("href", "/app/user/" + res.reviewer.id);
                        $item.find("a[data-template='reviewerName']").text(res.reviewer.profile.name);
                        $item.find("a[data-template='reviewerName']").attr("href", "/app/user/" + res.reviewer.id);
                        $item.find("a[data-template='reviewTitle']").text(res.title);
                        $item.find("a[data-template='reviewTitle']").attr("href", "/app/noodle/{{noodle.id}}?focusReview=" + res.id);
                        $item.find("span[data-template='rating']").text(res.rating);
                        $item.find("p[data-template='reviewBody']").text(res.body);
                        $item.find("span[data-template='reviewTime']").text(res.created);

                        if (res.images.length != 0) {
                            $item.find("div[data-template='reviewImages']").removeClass("d-none");
                        }
                        res.images.forEach(function (item){
                            $item.find("div[data-template='reviewImages']").append(
                                "<a href=\"" + item.image + "\"><img src=\"" + item.image +"\" height=\"150\"></a>" 
                            );
                        });
                        

                        $("#reviewList").append($item);
                        console.log(res)
                        $("#showAllReviews").removeClass("d-none");

                        document.querySelector('#reviewList').scrollIntoView({});
                }
            },
            403: function(){
                $("#error-text").removeClass("d-none");
                $("#error-text").html("Error retrieving notifications");
            }
        }
    });
}

$(document).ready(function(){
    function getUrlVars()
    {
        var vars = [], hash;
        var hashes = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');
        for(var i = 0; i < hashes.length; i++)
        {
            hash = hashes[i].split('=');
            vars.push(hash[0]);
            vars[hash[0]] = hash[1];
        }
        return vars;
    }
    
    var urlVars = getUrlVars();
    if (urlVars.focusReview) {
        focusReview(urlVars.focusReview)
    } else if (urlVars.scrollToReviews) {
        document.querySelector('#reviewList').scrollIntoView({});
        allReviews();
    } else {
        allReviews();
    }
});
</script>

<template id="reviewTemplate">
    <li class="media mt-2">
        <a data-template="reviewItem" href="#">
            <img data-template="reviewerImg" class="img-fluid img-thumbnail mr-3" style="height: 6em;" src="">
        </a>
        <div class="media-body">
            <strong><a data-template="reviewerName"></a> says <a data-template="reviewTitle"></a></strong><br />
            <small>Rated <span data-template="rating"></span> stars</small>
            <p data-template="reviewBody"></p>
            <div data-template="reviewImages" class="d-none"></div>
            <small>Posted: <span data-template="reviewTime"></span></small>
        </div>
    </li>
</template>

{% endblock %}
{% block page %}
<div class="container">
<h1>{{noodle.name}}</h1>

{% comment %} This provides an image carousel that keeps images from being too large for page {% endcomment %}
<div id="carouselControls" class="carousel slide" data-ride="carousel" style="width: 100%; max-width: 30em; !important">
    <div class="carousel-inner">
        {%for image_obj in noodle.noodleimage_set.all%}
        <div class="carousel-item {% if forloop.counter == 1 %}active{% endif %}">
            <img class="d-block w-100" src="{{ MEDIA_URL }}{{ image_obj.image.name }}">
        </div>
        {% endfor %}
    </div>
    <a class="carousel-control-prev" href="#carouselControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<h2>Information</h2>
<table class="table">
    <tbody>
        {% for key, value in noodle.metadata.items %}
        <tr>
            <td>{{key}}</td>
            <td>{{value}}</td>
        </tr>
        {% endfor %}

        <tr>
            <td>Rating</td>
            <td>{{avg_rating}} stars from {{noodle.review_set.all|length}} ratings</td>
        </tr>

        <tr>
            <td>Tags</td>
            <td>
            {% for tag in noodle.tags.all %}
                <a href="{% url 'search' %}?tags={{tag.name}}">
                    <span class="badge badge-info">{{tag.name}}</span>
                </a>
            {% endfor %}
            </td>
    </tbody>
</table>

{% if user.is_authenticated %}
<h2>Actions</h2>
<div id="actionsSection">
<div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" 
            id="listsMenuButton" data-toggle="dropdown" aria-haspopups="true" aria-expanded="false"
            >Add to list</button>
    <div id="listAddDropdown" class="dropdown-menu" aria-labelledby="listsMenuButton">
    </div>
</div>
</div>

{% url 'noodle_report' noodle.id as report_link%}
<a class="btn btn-danger mt-2" href={{report_link}} role="button">Report</a>

{% url 'edit_ramen' noodle.id as edit_link %}
<a class="btn btn-primary mt-2" href="{{edit_link}}">Edit Noodle</a>

<hr />
{% endif %}

<h2>Reviews</h2>
<small id="error-text" class="d-none">Error!</small>
<a id="showAllReviews" href="{% url 'noodle' noodle.id %}?scrollToReviews=1" class="d-none">Show All Reviews</a>
<ul id="reviewList" class="list-unstyled">

</ul>

<h4>Add Review</h4>

<form enctype="multipart/form-data" method="post" action="{% url 'review_ramen' noodle.id %}">
    {% csrf_token %}
    <table>
    <tr>
        <td>{{ form.title.label_tag }}</td>
        <td>{{ form.title }}</td>
    </tr>
    <tr>
        <td>{{ form.body.label_tag }}</td>
        <td>{{ form.body }}</td>
    </tr>
    <tr>
        <td>{{ form.rating.label_tag }}</td>
        <td>{{ form.rating }}</td>
    </tr>
    <tr>
        <td>{{ form.image.label_tag }}</td>
        <td>{{ form.image }}</td>
    </tr>
    </table>
    {% if request.user.is_authenticated %}
        <input type="submit" value="Add Review">
    {% else %}
        {% url 'login' as login_link%}
        <a class="btn btn-primary" href="{{login_link}}?next={{request.path}}" role="button">Login to Review</a>
    {% endif %}
    </form>


</div>

{% endblock %}

rameniaapp/templates/report.html
{% extends "base.html" %}
{% block page %}
<center>
<h1>Reported {{ item_type }}</h1>
<ul class="list-group">
<li class="list-group-item">
    {% for report in reports %}
        <p> Report #{{ report.id }}:
        {% if report.type == "RV" %}
            {% url 'review' report.review.id as review_link %}
            <a href={{review_link}}>{{ report.review.title }}</a>
        {% elif report.type == "ND" %}
            {% url 'noodle' report.noodle.id as noodle_link %}
            <a href={{noodle_link}}>{{ report.noodle.name }}</a>
        {% elif report.type == "PF" %}
            {% url 'profile' report.profile.user.id as profile_link %}
            <a href={{profile_link}}>{{ report.profile.name }}</a>
        {% endif %}
        </p>
        <span class="badge badge-primary badge-pill">{{ report.get_reason_display }}</span>
        <span class="badge badge-primary badge-pill">{{ report.get_status_display }}</span>
    </li>
    {% endfor %}
</ul>
</center>
{% comment %} {% for report in reports %}
<ul class="list-unstyled">
<li class="media">
    <a href="{% url 'noodle' noodle.id %}">
        <img class="img-fluid img-thumbnail mr-3" style="height: 6em;" src="{{MEDIA_URL}}{{ image.image.name }}">
    </a>
    <div class="media-body">
        <a href="{% url 'noodle' noodle.id %}">
            <h5 class="mt-0">{{ noodle.name }}</h5>
        </a>
        Rating: {{ score }}/5 from {{noodle.review_set.all|length}} ratings <br />
        {% for tag in noodle.tags.all %}
            <span class="badge badge-info">{{tag.name}}</span>
        {% endfor %}

        {% if user.is_authenticated and user.id == listinfo.user.id %}
        <br />
        <button type="button" data-noodle-id="{{noodle.id}}"
                class="entry-remove btn btn-danger btn-sm">Remove</button>
        {% endif %}
    </div>
</li>
</ul>
{% endfor %} {% endcomment %}

{% endblock %}